### ISSUE TITLE
1 visitor-multiple session

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/statslive#20]
prestashop 1.7.5.0
Debian 4.9.110-3+deb9u2  x86_64
php 7.2.14
MySQL: 10.1.37-MariaDB-0+deb9u1
as you can see on this document https://1drv.ms/t/s!AnkbspQIR_C66z8seujS3BVYK89d for every visitor (IP) prestashop have a large number of session with the same IP
It's normal? or it's an issue?

**Comment by matks** [comment]
This repository is being archived so I close this issue.
